server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jb_crm_team0?useUnicode=true&charsetEncoding=utf-8
    username: root
    password: root
  application:
    name: customer-service
  redis:
    host: localhost
    post: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
management:
  security:
    enabled: false
logging:
  level:
    org:
      ydy:
        mapper: debug